#!/usr/bin/env sh
#website - set up website with nginx or apache
set -eu

echo() { printf "%s" "$*"; }

lineinfile() { #1: path, 2: regexp, 3: line
    [ $# -eq 2 ] && set -- "$1" "^$2\$" "${3:-$2}" || true
    if grep -qF "^$3$" "$1" 2>/dev/null; then
        return
    elif grep -q "$2" "$1" 2>/dev/null; then
        set -- "$1" "$2" "$3" "$(mktemp)"
        sed "s/.*$(echo "$2"|sed 's_/_\\/_').*/$(echo "$3"|sed 's_/_\\/_')/" \
            <"$1" >"$4"
        sudo mv "$4" "$1"
    else
        sudo sh -c 'echo "$3" >>"$1"' - "$@"
    fi
}

[ -n "$HTTPD" ] || { echo "error: set HTTPD to apache or nginx"; exit 1; }
TYPE="${TYPE:-fileserver}"
SITENAME="${SITENAME:-$HOSTNAME${PORT+-$PORT}}"
LOCATION="${LOCATION:-/srv/http/$SITENAME}"
PORT="${PORT:-80}"

sudo mkdir -p "$LOCATION"

case "$HTTPD" in
apache)
    <"website/apache-$TYPE" \
        sed \
            -e "s/\\\$SITENAME/$SITENAME/" \
            -e "s/\\\$PORT/$PORT/" \
            -e "s \\\$LOCATION $LOCATION " \
        | sudo tee "/etc/httpd/conf/vhosts/$SITENAME.conf" >/dev/null
    cat /etc/httpd/conf/vhosts/*.conf \
        | sed -n 's/<VirtualHost [^: \/]*:\([0-9]*\)>.*/Listen \1/p' \
        | sudo tee /etc/httpd/conf/ports.conf >/dev/null
    sudo systemctl restart httpd
    ;;
nginx)
    <"website/nginx-$TYPE" \
        sed \
            -e "s/\\\$SITENAME/$SITENAME/" \
            -e "s/\\\$PORT/$PORT/" \
            -e "s \\\$LOCATION $LOCATION " \
        | sudo tee "/etc/nginx/sites-available/$SITENAME" >/dev/null
    sudo ln -sf "/etc/nginx/sites-available/$SITENAME" \
        "/etc/nginx/sites-enabled/$SITENAME"
    sudo systemctl reload nginx || sudo systemctl restart nginx || true
    ;;
esac

