#!/usr/bin/env sh
#bootstrap - create account and such

sudo pacman -q --noconfirm -S --needed openssh alacritty-terminfo
sudo cp base/sshd_config /etc/ssh/sshd_config
sudo systemctl enable --now sshd
sudo systemctl reload sshd
sudo cp base/sudoers /etc/sudoers
