#!/usr/bin/env sh
#base - set up ssh/package manager

case "$(uname -s)" in
Darwin)
    sudo systemsetup -f -setremotelogin on
    command -v brew >/dev/null 2>&1 || ruby -e "$(curl -fsSL \
        https://raw.githubusercontent.com/Homebrew/install/master/install)"
    ;;
Linux)
    sudo pacman -q --noconfirm -S --needed openssh
    sudo cp base/sshd_config /etc/ssh/sshd_config
    sudo systemctl enable --now sshd
    sudo systemctl reload sshd
    sudo cp base/sudoers /etc/sudoers
    ;;
esac
