#!/usr/bin/env sh
#dotnet - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists dotnet; then
    if exists pacman; then sudo pacman --needed --noconfirm -qS dotnet-sdk;
    elif exists brew; then brew cask install dotnet-sdk; fi
fi

dotnet "$@"
