#!/usr/bin/env sh
#go - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists go; then
    if exists pacman; then sudo pacman --needed --noconfirm -qS go;
    elif exists brew; then brew install go;
    elif exists apk; then sudo apk add -q go;
    elif exists apt-get; then sudo apt-get install -qy golang-go; fi
fi

go "$@"
