#!/usr/bin/env sh
#mix - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists mix; then
    if exists brew; then brew install elixir; fi
    if exists pacman; then sudo pacman --needed --noconfirm -qS elixir; fi
    if exists apk; then sudo apk add -q elixir; fi
fi

mix "$@"

