#!/usr/bin/env sh
#npm - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists npm; then
    if exists brew; then brew install npm; fi
    if exists pacman; then sudo pacman --needed --noconfirm -qS npm; fi
    if exists apk; then sudo apk add -q npm; fi
fi

npm "$@"
