#!/usr/bin/env sh
#pass - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists pass; then
    if exists apk; then sudo apk add gnupg >&2; fi
    if exists pacman; then sudo pacman --needed --noconfirm -qS gnupg >&2; fi
    if exists brew; then brew install gnupg >&2; fi
    workingdir="$(mktemp -d)"
    cd "$workingdir"
    git clone --recurse-submodules https://github.com/milhnl/pass.git
    cd pass
    make PREFIX="$PREFIX" install >&2
    cd
    rm -rf "$workingdir"
fi

pass "$@"

