#!/usr/bin/env sh
#titlecase - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists titlecase; then
    pip3 install --user titlecase
fi

titlecase "$@"
