#!/usr/bin/env sh
#init - create user, only secure ssh access, install package managers and sudo
set -eu

die() { if [ "$#" -gt 0 ]; then printf "%s" "$*" >&2; fi; exit 1; }
exists() { command -v "$1" >/dev/null 2>&1; }
[ $(id -u) = 0 ] && ! exists sudo && sudo() { "$@"; } || true #just run as root
rndpasswd() {
    </dev/urandom \
        LC_CTYPE=C tr -cd A-Za-z0-9 \
        | head -c64 \
        | sed p \
        | sudo passwd "${1:-root}" >/dev/null 2>&1 \
        || die "Can't lock password for ${1:-root}"
}

#Initialize package managers
case "$(uname -s)" in
Darwin)
    if ! exists brew; then
        URL="https://raw.githubusercontent.com/Homebrew/install/master/install"
        ruby -e "$(curl -fsSL "$URL")" || die "Homebrew installation failed"
    fi;;
Linux)
    if exists pacman; then
        sudo pacman-key --init
        sudo pacman-key --populate \
            "archlinux$(uname -m | sed -n 's/\(armv7l\|aarch64\)/arm/p')"
    fi;;
esac

#Install zsh
if exists pacman; then
    sudo pacman --needed --noconfirm -qS zsh
elif exists apk; then
    sudo apk -q add zsh
elif exists apt-get; then
    sudo apt-get install -qy zsh
fi

#Create user
if ! id -u mil >/dev/null 2>&1; then
    if exists useradd; then
        sudo groupadd wheel
        sudo useradd -s "$(command -v zsh)" -G wheel -m mil
    elif exists adduser; then
        sudo adduser -s "$(command -v zsh)" -G wheel -D mil
    fi
    id -u mil >/dev/null 2>&1 || die "Can't add user mil"
    rndpasswd mil
fi

#Copy ssh public key
mkdir -p ~mil/.ssh
cp init/authorized_keys ~mil/.ssh/authorized_keys
chown -R mil ~mil/.ssh
chmod -R og-rwxs ~mil/.ssh

#Install and configure sshd
sudo cp init/sshd_config /etc/ssh/sshd_config
case "$(uname -s)" in
Darwin)
    sudo systemsetup -f -setremotelogin on
    ;;
Linux)
    sudo cp init/sudoers /etc/sudoers
    if exists pacman; then
        sudo pacman --needed --noconfirm -qS openssh sudo
        sudo systemctl enable --now sshd
        sudo systemctl reload sshd
    elif exists apk; then
        sudo apk -q add openssh sudo
    elif exists apt-get; then
        sudo apt-get install -qy openssh-server sudo
        sudo systemctl enable --now ssh
        sudo systemctl reload ssh
    fi
    unset -f sudo
    exists sudo && ps -A | grep -q sshd || die "sudo/ssh setup failed"
    rndpasswd root
    ;;
esac

#Remove set-up user
if id -u alarm >/dev/null 2>&1; then
    sudo userdel -f alarm >/dev/null 2>&1
fi

#Set hostname
if ! expr localhost = "$HOSTNAME" \| "$HOSTNAME" : '[0-9.]*$' >/dev/null; then
    echo "$HOSTNAME" | sed 's/\..*//' | sudo tee /etc/hostname >/dev/null
    if [ "$(uname -s)" = Darwin ]; then
        for name in HostName LocalHostName ComputerName; do
            sudo scutil --set "$name" "$HOSTNAME"
        done
        sudo dscacheutil -flushcache
    fi
fi

#Synchronise time
if exists pacman; then
    sudo pacman --noconfirm --needed -qS ntp
    sudo systemctl enable --now ntpd
fi
