#!/usr/bin/env sh
#mdns - install and configure mdns (avahi)
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }
sponge() { set -- "$1" "$(mktemp)"; cat >"$2"; sudo mv "$2" "$1"; }

if exists pacman; then sudo pacman --needed --noconfirm -qS nss-mdns;
elif exists apt; then sudo apt install avahi-daemon; fi
sudo systemctl enable --now avahi-daemon

</etc/nsswitch.conf \
    sed '/^hosts: /s/ \(resolve\|dns\) / mdns_minimal [NOTFOUND=return] \1 /' \
    | sponge /etc/nsswitch.conf
