Vagrant.configure("2") do |config|
  config.vm.box = "peru/windows-10-enterprise-x64-eval"
  config.vm.define "$HOSTNAME"

  config.vm.network "forwarded_port", guest: 8079, host: $HOST_HTTP_PORT
  config.vm.network "forwarded_port", guest: 22, host: $HOST_SSH_PORT
  config.vm.network "forwarded_port", guest: 24, host: $HOST_WSSH_PORT
  config.vm.network "forwarded_port", guest: 3389, host: $HOST_RDP_PORT

  config.vm.provider "virtualbox" do |vb|
    vb.name = "$HOSTNAME"
    vb.memory = 6144
    vb.cpus = 2
    vb.gui = false
  end

  config.vm.provision "shell", path: "provision.ps1"
end
