#!/usr/bin/env sh
#desktop - install desktop programs and configuration

case "$(uname -s)" in
Linux)
    sudo pacman -q --noconfirm -S --needed \
        sway waybar swaylock wl-clipboard firefox firefox-ublock-origin \
        alacritty alacritty-terminfo
    ;;
Darwin)
    #Tap-to-click
    defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
    sudo defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad \
        Clicking -bool true
    sudo defaults -currentHost write NSGlobalDomain \
        com.apple.mouse.tapBehavior -int 1
    #Style
    sudo defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    defaults write NSGlobalDomain AppleHighlightColor \
        "0.847059 0.847059 0.862745";
    defaults write NSGlobalDomain AppleInterfaceStyle Dark
    defaults write NSGlobalDomain AppleAquaColorVariant 6
    defaults write NSGlobalDomain _HIHideMenuBar -bool true
    defaults write com.apple.dock autohide -bool true && \
    defaults write com.apple.dock autohide-delay -float 1000 && \
    defaults write com.apple.dock no-bouncing -bool TRUE && \
    defaults write com.apple.dock mru-spaces -bool false && \
        killall Dock
    defaults write com.apple.finder QuitMenuItem -bool true && \
        killall Finder
    killall Dock SystemUIServer
    defaults write com.apple.Terminal FocusFollowsMouse -string YES
    #Default software
    brew cask install darktable whatsapp
    ;;
esac
