#!/usr/bin/env sh
#music - install mpd, shairport-sync and set them up

grep -q "dtparam=audio=on" 2>/dev/null \
    || echo " dtparam=audio=on" | sudo tee -a /boot/config.txt >/dev/null
sudo pacman -q --noconfirm -S --needed shairport-sync mpd alsa-utils
sudo cp music/asound.conf /etc/asound.conf
sudo cp music/mpd.conf /etc/mpd.conf
sudo usermod -aG audio mpd
sudo systemctl enable --now shairport-sync mpd
