#!/usr/bin/env sh
#dev - install and configure development programs

case "$(uname -s)" in
Linux)
    sudo pacman -q --noconfirm -S --needed base-devel go git vis tig fzy pass
    ;;
Darwin)
    brew install go vis tig fzy pass
    ;;
esac
