#!/usr/bin/env sh
#home - set up home directory
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }
exists apk && sudo apk add curl ncurses git make
exists pacman && sudo pacman -qS --needed --noconfirm git make

if ! [ -x "/etc/ssl/ca-certificates.crt" ] && exists pacman; then
    sudo pacman -qS --needed --noconfirm ca-certificates-utils
fi

#Set env
set -a
case "$(uname -s)" in
Darwin)
    PREFIX="$HOME/Library/Local"
    XDG_CACHE_HOME="$HOME/Library/Caches"
    XDG_CONFIG_HOME="$HOME/Application Support"
    ;;
Linux)
    PREFIX="$HOME/.local"
    XDG_CACHE_HOME="$HOME/.cache"
    XDG_CONFIG_HOME="$HOME/.config"
    ;;
esac
XDG_DATA_HOME="$PREFIX/share"
XDG_BIN_HOME="$PREFIX/bin"
GNUPGHOME="$XDG_CONFIG_HOME/gpg"
TERMINFO="$XDG_DATA_HOME/terminfo"

#Install terminfo for alacritty
alacritty_info="$(mktemp)"
curl "$(printf "%s%s" 'https://raw.githubusercontent.com' \
    '/jwilm/alacritty/master/extra/alacritty.info')" >"$alacritty_info"
tic -xe alacritty,alacritty-direct "$alacritty_info"
rm "$alacritty_info"

#Clone dotfiles and install
[ -d "$PREFIX/dot" ] \
    || git clone https://milhnl@github.com/milhnl/dotfiles "$PREFIX/dot" \
    && (cd "$PREFIX/dot" && make link)

#Set up gpg
chmod go-rwx "$GNUPGHOME" >/dev/null 2>&1
if exists gpg && [ $(gpg --list-secret-keys | wc -l 2>/dev/null) = 0 ]; then
    killall -s SIGKILL gpg-agent >/dev/null 2>&1 || true
    #generate with gpg --export-secret-keys -a >"$GNUPGHOME/keys.asc"
    gpg --batch --import "$GNUPGHOME/keys.asc" 2>/dev/null
    echo "$(gpg --list-keys --fingerprint 2>/dev/null \
        | grep "michiel@vdnheuvel.com" -B 1 | sed 's/ //g; s/.*=//; 1q' \
    ):6:" | gpg --import-ownertrust 1>/dev/null 2>/dev/null
fi

echo "hsts-file = $XDG_CACHE_HOME/wget-hsts" >"$XDG_CONFIG_HOME/wgetrc"
