#!/usr/bin/env sh
#home - set up home directory
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }
exists apk && sudo apk add curl ncurses git make
exists pacman && sudo pacman -qS --needed --noconfirm git make

if ! [ -x "/etc/ssl/ca-certificates.crt" ] && exists pacman; then
    sudo pacman -qS --needed --noconfirm ca-certificates-utils
fi

#Install terminfo for alacritty
ALACRITTY_INFO="$(mktemp)"
curl "$(printf "%s%s" 'https://raw.githubusercontent.com' \
    '/jwilm/alacritty/master/extra/alacritty.info')" >"$ALACRITTY_INFO"
tic -xe alacritty,alacritty-direct "$ALACRITTY_INFO"
rm "$ALACRITTY_INFO"

#Clone dotfiles and install
set -a
case "$(uname -s)" in
Darwin)
    PREFIX="$HOME/Library/Local"
    XDG_BIN_HOME="$PREFIX/bin"
    XDG_CACHE_HOME="$HOME/Library/Caches"
    XDG_CONFIG_HOME="$HOME/Application Support"
    XDG_DATA_HOME="$PREFIX/share"
    ;;
Linux)
    PREFIX="$HOME/.local"
    XDG_BIN_HOME="$PREFIX/bin"
    XDG_CACHE_HOME="$HOME/.cache"
    XDG_CONFIG_HOME="$HOME/.config"
    XDG_DATA_HOME="$PREFIX/share"
    ;;
esac

[ -d "$PREFIX/dot" ] \
    || git clone https://milhnl@github.com/milhnl/dotfiles "$PREFIX/dot" \
    && (cd "$PREFIX/dot" && make link)
