#!/usr/bin/env sh
set -eu

PATH="$PATH:/System/Library/PrivateFrameworks/Apple80211.framework"
PATH="$PATH/Versions/A/Resources"

case `uname -s` in
Darwin)
    airport -I | sed -n 's/ *BSSID: //p';;
Linux)
    iwconfig 2>/dev/null \
        | sed -n 's/.*Access Point: \([0-9\:A-F]\{17\}\).*/\1/p' \
        | tr A-F a-f;;
esac
