#!/usr/bin/env sh
#dot - manage dotfiles

REPO="$PREFIX/dot"

if sed -n 's/^.PHONY:[[:blank:]]*//p' <"$REPO/Makefile" | grep -q "$1"; then
    (cd "$REPO"; make "$1")
elif find "$(git --exec-path)" -name 'git-*' 2>/dev/null \
        | grep -q "^.*/git-$1\$"; then
    git -C "$REPO" "$@"
elif [ "$1" = edit ]; then
    "$EDITOR" "$REPO/$(git -C "$REPO" ls-files | grep "$2" | sed 1q)"
else
    (cd "$REPO"; "$@")
fi
