#!/usr/bin/env sh
#editor - pick the right editor and launch it

exists() { command -v "$1" >/dev/null 2>&1; }
fnmatch() { case "$2" in $1) return 0 ;; *) return 1 ;; esac ; }
sponge() { set -- "$1" "$(mktemp)"; cat >"$2"; mv "$2" "$1"; }

encoding() {
    head -n1 "$1" 2>/dev/null | awk '
        /^\357\273\277/ && NR == 1 { printf "b"; }
        /\r$/ && NR == 1 { printf "c"; }'
}

clean() {
    sed -e "$(printf 's/\r$//; 1s/^\xef\xbb\xbf//')" "$@"
}

dirty() {
    if fnmatch '*b*' "$1"; then printf '1s/^/\xef\xbb\xbf/;'; fi
    if fnmatch '*c*' "$1"; then printf 's/$/\r/;'; fi
}

ewrap1() {
    printf "\e]0;edit %s\a" "$1"
    if test -e "$1" && ! test -w "$1"; then
        sudo sh -c "
            export XDG_CONFIG_HOME='$XDG_CONFIG_HOME'
            export VIS_PATH='$XDG_CONFIG_HOME/vis'
            '$(command -v editor)' \"$@\"
        " -- "$@"
    else
        if [ "$(uname -s)" = Darwin ] && exists vise; then
            export EDITOR=vise
        elif exists vis; then
            export EDITOR=vis
        elif exists vim; then
            export EDITOR=vim
        else
            export EDITOR=vi
        fi
        "$EDITOR" "$@"
    fi
}

ewrap0() {
    [ "$1" = -- ] && shift
    ENCODING="$(encoding "$1")"
    if [ -f "$1" ] && [ -n "$ENCODING" ]; then
        case "$(uname -s)" in
        Darwin)
            clean -i '' "$1"
            ewrap1 "$@"
            sed -e "$(dirty "$ENCODING")" -i '' "$1"
            ;;
        Linux)
            clean -i "$1"
            ewrap1 "$@"
            sed -e "$(dirty "$ENCODING")" -i "$1"
            ;;
        *)
            <"$1" clean | sponge "$1"
            ewrap1 "$@"
            <"$1" sed -e "$(dirty "$ENCODING")" | sponge "$1"
            ;;
        esac
    else
        ewrap1 "$@"
    fi
}

devenv() {
    ("$(wslpath -u "$(vswhere.exe -property productPath|tr -d \\r)")" "$@" \
        >/dev/null 2>&1 &)
}

rider() {
    (cmd.exe /c "rider '$1' '$2'" >/dev/null 2>&1 &)
}

editor() {
    if ! exists vise && [ "$(uname -s)" = Darwin ] || ! exists vis; then
        exists pacman && sudo pacman --needed --noconfirm -qS vis
        exists apk && sudo apk -q add vis
        exists apt-get && sudo apt-get -qy install vis
        exists brew && brew install vis
    fi
    case "$1" in 
    *.cs|*.cshtml)
        if tasklist.exe 2>/dev/null | grep -q devenv.exe; then
            devenv /edit "$(wslpath -w "$1")"
        elif cmd.exe /c 'where rider' >/dev/null 2>&1; then
            rider "$(upwardfind "$1" '*.sln')" "$(wslpath -w "$1")"
        elif command -v vswhere.exe >/dev/null 2>&1; then
            devenv "$(wslpath -w "$(upwardfind "$1" '*.sln')")"
        else
            ewrap0 "$@"
        fi
        ;;
    *.sln|*.csproj)
        if tasklist.exe 2>/dev/null | grep -q devenv; then
            devenv "$(wslpath -w "$1")"
        elif cmd.exe /c 'where rider' >/dev/null 2>&1; then
            rider "$(wslpath -w "$1")"
        elif command -v vswhere.exe >/dev/null 2>&1; then
            devenv "$(wslpath -w "$1")"
        else
            ewrap0 "$@"
        fi
        ;;
    *) ewrap0 "$@" ;;
    esac
}

editor "$@"
