#!/usr/bin/env sh
#editor - pick the right editor and launch it

exists() { command -v "$1" >/dev/null 2>&1; }

ewrap1() {
    printf "\e]0;edit %s\a" "$1"
    if test -e "$1" && ! test -w "$1"; then
        sudo sh -c "
            export XDG_CONFIG_HOME='$XDG_CONFIG_HOME'
            export VIS_PATH='$XDG_CONFIG_HOME/vis'
            '$(command -v editor)' \"$@\"
        " -- "$@"
    else
        if [ "$(uname -s)" = Darwin ] && exists vise; then
            export EDITOR=vise
        elif exists vis; then
            export EDITOR=vis
        elif exists vim; then
            export EDITOR=vim
        else
            export EDITOR=vi
        fi
        "$EDITOR" "$@"
    fi
}

ewrap0() {
    [ "$1" = -- ] && shift
    if test -f "$1" && grep -q "$(printf '\357\273\277')" "$1"; then
        sed -e "$(printf 's/\r$//; 1s/^\xef\xbb\xbf//')" -i "$@"
        ewrap1 "$1"
        sed -e "$(printf '1s/^/\xef\xbb\xbf/')" -i "$@"
    else
        ewrap1 "$@"
    fi
}

devenv() {
    ("$(wslpath -u "$(vswhere.exe -property productPath|tr -d \\r)")" "$@" \
        >/dev/null 2>&1 &)
}

rider() {
    (cmd.exe /c "rider '$1' '$2'" >/dev/null 2>&1 &)
}

editor() {
    if ! exists vise && [ "$(uname -s)" = Darwin ] || ! exists vis; then
        exists pacman && sudo pacman --needed --noconfirm -qS vis
        exists apk && sudo apk -q add vis
        exists apt-get && sudo apt-get -qy install vis
        exists brew && brew install vis
    fi
    case "$1" in 
    *.cs|*.cshtml)
        if tasklist.exe 2>/dev/null | grep -q devenv.exe; then
            devenv /edit "$(wslpath -w "$1")"
        elif cmd.exe /c 'where rider' >/dev/null 2>&1; then
            rider "$(upwardfind "$1" '*.sln')" "$(wslpath -w "$1")"
        elif command -v vswhere.exe >/dev/null 2>&1; then
            devenv "$(wslpath -w "$(upwardfind "$1" '*.sln')")"
        else
            ewrap0 "$@"
        fi
        ;;
    *.sln|*.csproj)
        if tasklist.exe 2>/dev/null | grep -q devenv; then
            devenv "$(wslpath -w "$1")"
        elif cmd.exe /c 'where rider' >/dev/null 2>&1; then
            rider "$(wslpath -w "$1")"
        elif command -v vswhere.exe >/dev/null 2>&1; then
            devenv "$(wslpath -w "$1")"
        else
            ewrap0 "$@"
        fi
        ;;
    *) ewrap0 "$@" ;;
    esac
}

editor "$@"
