#!/usr/bin/env sh
#gpgunlock - prompt for passphrase
set -eu

gpgunlock() {
    export GPG_TTY="$(tty)"
    gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1
    killall pinentry >/dev/null 2>&1 || true
    killall pinentry-curses >/dev/null 2>&1 || true
    ssh localhost true
    printf "" \
        | gpg -qe --yes --default-recipient-self -o- \
        | gpg -qd
}

gpgunlock
