#!/usr/bin/env sh
set -eu

quote() {
    for x do
        printf %s\\n "$x" \
            | sed "s/[[|&;<>()\\\$\`\\\\\"' $(printf '\t')*?#~=%]/\\\\&/g;
                s/\$/ \\\\/"
    done
    echo " "
}

while getopts "u:" OPT "$@"; do
    case "$OPT" in
    u) REMOTE_USER="$OPTARG";;
    esac
done

shift "$(( $OPTIND - 1 ))"
HOST="${1:-$REMOTE_HOST}"
shift
CMD="$(quote "$@" | sed "s/'/'\\\\''/g")"

ssh -t "$HOST" sudo -u "${REMOTE_USER:-unattended}" sh -lic "'
    set -a
    XDG_RUNTIME_DIR=\"/run/user/\$(id -u)\"
    SWAYSOCK=\"\$XDG_RUNTIME_DIR/sway-ipc.\$(id -u).\$(pidof sway).sock\"
    WAYLAND_DISPLAY=wayland-0
    MOZ_ENABLE_WAYLAND=1
    exec $CMD
'"