#!/usr/bin/env sh
#m - do all the things with mail

lock() { mkdir "$XDG_RUNTIME_DIR/mdaemon"; }
unlock() { rmdir "$XDG_RUNTIME_DIR/mdaemon"; }
sponge() { set -- "$1" "$(mktemp)"; cat >"$2"; mv "$2" "$1"; }

make_ish() { #1: old, 2: new, 3... cmd
    if [ -z "$(find -L "$2" -newer "$1" -exec echo 1 \; 2>/dev/null)" ]; then
        <"$1" sh -c 'shift 2; exec "$@"' -- "$@" | sponge "$2"
    fi
}

m_sync() {
    [ "$#" -eq 0 ] && set -- -a
    mkdir -p "$PREFIX/var/mail/gmail"
    mkdir -p "$PREFIX/var/mail/eforah"
    mkdir -p "$PREFIX/var/mail/radboud"

    MBSYNCRC="$XDG_CONFIG_HOME/isync/mbsyncrc"
    if [ "$(lsb_release -sir)" = "Ubuntu 16.04" ]; then
        make_ish "$MBSYNCRC" "$MBSYNCRC-16.04" sed 's/^SSLType.*/UseIMAPS yes/'
        MBSYNCRC="$MBSYNCRC-16.04"
    elif [ "$(uname -s)" = "Darwin" ]; then
        make_ish "$MBSYNCRC" "$MBSYNCRC-Darwin" sed \
            -e 's|CertificateFile.*|CertificateFile "/etc/ssl/cert.pem"|' \
            -e 's|~/.local|'"$PREFIX"'|'
        MBSYNCRC="$MBSYNCRC-Darwin"
    fi

    if lock mdaemon; then
        trap unlock EXIT
        mbsync -c "$MBSYNCRC" "$@"
        notmuch new
        unlock
    fi
}

m_daemon() {
    while true; do
        m_sync "$@"
        if [ "$(notmuch count tag:unread AND NOT tag:killed)" -gt 0 ]; then
            notmuch show --format=mbox tag:unread AND NOT tag:killed \
                | sed -n 's/^Subject: //p' \
                | while read -r REPLY; do
                    notify-send -t 10000 -u low "You've Got Mail" "$REPLY"
                done
        fi
        if pgrep -q ScreenSaverEngine; then
            exit 0
        fi
        sleep 60
    done
}

m_view() {
    alot -p "$MAILDIR" -c "$XDG_CONFIG_HOME/alot/config" "$@"
}

(pgrep -f 'mail_client daemon' || mail_client daemon&) >/dev/null 2>&1
if [ "$#" -eq 0 ]; then set -- view; fi
case "$1" in
sync) shift; m_sync "$@";;
daemon) shift; m_daemon "$@";;
view) shift; m_view "$@";;
*) notmuch "$@";;
esac
