#!/usr/bin/env sh
#matrix_client - do all the things with matrix
set -eu

pick() {
    IFS= read -r line1 && IFS= read -r line2 || true
    if [ -n "${line1:-}" ] && [ -n "${line2:-}" ]; then
        { echo "$line1"; echo "$line2"; cat -; } | fzy "$@"
    else
        echo "$line1"
    fi
}

isodate() {
    if [ "${#2}" -eq 1 ]; then set -- "$1" "0$2"; fi
    case "$1" in
    Jan) echo "01-$2";;
    Feb) echo "02-$2";;
    Mar) echo "03-$2";;
    Apr) echo "04-$2";;
    May) echo "05-$2";;
    Jun) echo "06-$2";;
    Jul) echo "07-$2";;
    Aug) echo "08-$2";;
    Sep) echo "09-$2";;
    Oct) echo "10-$2";;
    Nov) echo "11-$2";;
    Dec) echo "12-$2";;
    esac
}

daemon() {
    if ! pgrep -f "mpmc -d $MPMC_HOME" >/dev/null 2>&1; then
        mkdir -p "$MPMC_HOME"
        (mpmc -d "$MPMC_HOME" \
            -s "$(pass show web/chat.eforah.nl | sed -n 's/^homeserver: //p')"\
            -u "$(pass show web/chat.eforah.nl | sed -n 's/^user: //p')" \
            -p 'pass show web/chat.eforah.nl|head -n1' \
            >"$MPMC_HOME/out" 2>>"$MPMC_HOME/log" </dev/null &)
        while ! [ -n "$(find $XDG_DATA_HOME/mpmc -mindepth 1 -type d)" ]; do
            sleep 1
            if ! pgrep -f "mpmc -d $MPMC_HOME" >/dev/null 2>&1; then
                echo "matrix_client: couldn't start daemon" >&2; exit 1;
            fi
        done
    fi
    ROOMS="$(\
        for x in "$MPMC_HOME"/*/*/\!*; do \
            echo "$(basename "$x") $(cat "$x/name" 2>/dev/null)"; \
        done | sed '/[^ ] $/d')"
}

send() {
    daemon
    mkdir -p "$XDG_CACHE_HOME/mpmc"
    SERVER="$(cd "$MPMC_HOME"; find . -mindepth 2 -maxdepth 2 -type d | pick)"
    SENDER="$(echo "$SERVER" | sed 's|.*/@\([^:]*\).*|\1|')"
    CROOM="$(cat "$XDG_CACHE_HOME/mpmc/room" 2>/dev/null || true)"
    ROOM="$(echo "$ROOMS" | cut -d" " -f2- \
        | ([ -n "$CROOM" ] \
            && sed "/$CROOM/d" | cat "$XDG_CACHE_HOME/mpmc/room" - || cat) \
        | pick -p "$SENDER -> ")"
    echo "$ROOM" >"$XDG_CACHE_HOME/mpmc/room"
    ROOMID="$(echo "$ROOMS" | sed -n "s/^\([^ ]*\) $ROOM\$/\1/p")"
    LC_TIME=POSIX ls -lrt "$MPMC_HOME"/*/*/$ROOMID/@*/\$* 2>/dev/null \
        | print | tail
    MESSAGE="$(bash -ic "read -ep '$SENDER -> $ROOM: ' MSG"'; echo "$MSG"')"
    [ -n "$MESSAGE" ]
    printf "%s\n" "$MESSAGE" >"$MPMC_HOME/${SERVER#./}/$ROOMID/in"
}

view() {
    daemon
    (
        LC_TIME=POSIX ls -lrt "$MPMC_HOME"/*/*/*/@*/\$* 2>/dev/null
        tail -fn0 "$MPMC_HOME/out" | while read -r x; do ls -l "$x"; done
    ) \
        | print
}

print() {
    CDATE="${CDATE:-$(date '+%h %-d')}"; CROOM="${CROOM:-}"
    COLUMNS="${COLUMNS:-$(tput cols)}"
    while read -r MODE LINKS USER GROUP SIZE MONTH DAY TIME FILE; do
        DATE="$MONTH $DAY"
        MSGID="${FILE##*/}"
        SENDER="${FILE%%/$MSGID}"; SENDER="${SENDER##*/}"
        ROOMID="${FILE%%/$SENDER/$MSGID}"; ROOMID="${ROOMID##*/}"
        SENDER="${SENDER##@}"; SENDER="${SENDER%%:*}"
        if [ "$DATE" != "$CDATE" ] || [ "$ROOMID" != "$CROOM" ]; then
            printf "%s \e[4m%s\e[0m\n" \
                "$([ "$DATE" != "$CDATE" ] && isodate $DATE || echo '     ')" \
                "$(echo "$ROOMS" | sed -n "s/^$ROOMID //p")"
        fi
        printf "\033[2m%s \033[1m%s\t\033[0m%s\n" \
            "$TIME" \
            "$SENDER" \
            "$(<"$FILE" fold -sw $(( $COLUMNS - 16 )) \
                | sed '/^$/d;2,$s/^/'"$(printf "\t\t")"'/')"
        CDATE="$DATE"
        CROOM="$ROOMID"
    done
}

MPMC_HOME="$XDG_DATA_HOME/mpmc"
"$@"
