#!/usr/bin/env sh
#matrix_client - do all the things with matrix
set -eu

pick() {
    IFS= read -r line1 && IFS= read -r line2 || true
    if [ -n "${line1:-}" ] && [ -n "${line2:-}" ]; then
        { echo "$line1"; echo "$line2"; cat -; } | fzy "$@"
    else
        echo "$line1"
    fi
}

daemon() {
    if ! pgrep -f "mpmc -d $MPMC_HOME" >/dev/null 2>&1; then
        mkdir -p "$MPMC_HOME"
        (mpmc -d "$MPMC_HOME" \
            -s "$(pass show web/chat.eforah.nl | sed -n 's/^homeserver: //p')"\
            -u "$(pass show web/chat.eforah.nl | sed -n 's/^user: //p')" \
            -p 'pass show web/chat.eforah.nl|head -n1' \
            >"$MPMC_HOME/out" 2>>"$MPMC_HOME/log" </dev/null &)
        while ! [ -n "$(find $XDG_DATA_HOME/mpmc -mindepth 1 -type d)" ]; do
            sleep 1
            if ! pgrep -f "mpmc -d $MPMC_HOME" >/dev/null 2>&1; then
                echo "matrix_client: couldn't start daemon" >&2; exit 1;
            fi
        done
    fi
    ROOMS="$(\
        for x in "$MPMC_HOME"/*/*/\!*; do \
            echo "$(basename "$x") $(cat "$x/name" 2>/dev/null)"; \
        done | sed '/[^ ] $/d')"
}

send() {
    daemon
    mkdir -p "$XDG_CACHE_HOME/mpmc"
    SERVER="$(cd "$MPMC_HOME"; find . -mindepth 2 -maxdepth 2 -type d | pick)"
    SENDER="$(echo "$SERVER" | sed 's|.*/@\([^:]*\).*|\1|')"
    CROOM="$(cat "$XDG_CACHE_HOME/mpmc/room" 2>/dev/null || true)"
    ROOM="$(echo "$ROOMS" | cut -d" " -f2- \
        | ([ -n "$CROOM" ] \
            && sed "/$CROOM/d" | cat "$XDG_CACHE_HOME/mpmc/room" - || cat) \
        | pick -p "$SENDER -> ")"
    echo "$ROOM" >"$XDG_CACHE_HOME/mpmc/room"
    ROOMID="$(echo "$ROOMS" | sed -n "s/ $ROOM\$//p")"
    MESSAGE="$(echo "" | fzy -p "$SENDER -> $ROOM: ")"
    [ -n "$MESSAGE" ]
    printf "%s\n" "$MESSAGE" >"$MPMC_HOME/${SERVER#./}/$ROOMID/in"
}

view() {
    daemon
    cd "$MPMC_HOME" || exit
    COLUMNS="${COLUMNS:-$(tput cols)}"

    CDATE="${CDATE:-$(date '+%h %-d')}"; CROOM="${CROOM:-}"
    (
        LC_TIME=POSIX ls -lrt "$MPMC_HOME"/*/*/*/@*/\$* 2>/dev/null; \
        env tail -fn0 "$MPMC_HOME/out" \
            | while read -r REPLY; do ls -l1 "$REPLY"; done
    ) | while read -r MODE LINKS USER GROUP SIZE MONTH DAY TIME FILE; do
        DATE="$MONTH $DAY"
        MSGID="${FILE##*/}"
        SENDER="${FILE%%/$MSGID}"; SENDER="${SENDER##*/}"
        ROOMID="${FILE%%/$SENDER/$MSGID}"; ROOMID="${ROOMID##*/}"
        ROOM="$(echo "$ROOMS" | sed -n "s/^$ROOMID //p")"
        SENDER="${SENDER##@}"; SENDER="${SENDER%%:*}"
        if [ "$DATE" != "$CDATE" ]; then
            printf "      \e[4m$ROOM ($DATE)\e[0m\n";
        elif [ "$ROOM" != "$CROOM" ]; then
            printf "      \e[4m$ROOM\e[0m\n";
        fi
        printf "\033[2m%s \033[1m%s\t\033[0m%s\n" \
            "$TIME" \
            "$SENDER" \
            "$(<"$FILE" fold -sw $(( $COLUMNS - 15 )) \
                | sed '/^$/d;2,$s/^/'"$(printf "\t\t")"'/')"
        CDATE="$DATE"
        CROOM="$ROOM"
    done
}

MPMC_HOME="$XDG_DATA_HOME/mpmc"
"$@"
