#!/usr/bin/env sh

[ "$#" -eq 0 ] && set -- -a
mkdir -p "$PREFIX/var/mail/gmail"
mkdir -p "$PREFIX/var/mail/eforah"
mkdir -p "$PREFIX/var/mail/radboud"
chmod go-rwx "$GNUPGHOME" >/dev/null 2>&1

if [ "$DISTRO" = "Ubuntu" ] && [ "$(lsb_release -sr)" = "16.04" ]; then
    <"$XDG_CONFIG_HOME/isync/mbsyncrc" \
        sed 's/^SSLType.*/UseIMAPS yes/' \
        >"$XDG_CONFIG_HOME/isync/mbsyncrc-old"
    mbsync -qc "$XDG_CONFIG_HOME/isync/mbsyncrc-old" "$@"
elif [ "$OS" = "Darwin" ]; then
    <"$XDG_CONFIG_HOME/isync/mbsyncrc" \
        sed '
            s|CertificateFile.*|CertificateFile "/etc/ssl/cert.pem"|;
            s|~/.local|'"$PREFIX"'|;
        ' \
        >"$XDG_CONFIG_HOME/isync/mbsyncrc-macos"
    mbsync -c "$XDG_CONFIG_HOME/isync/mbsyncrc-macos" "$@"
else
    mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc "$@"
fi
