#!/usr/bin/env sh
set -e

exists() { command -v "$1" >/dev/null 2>&1; }
vc_copy() { printf "%s" "System clipboard not supported" >&2; exit 1; }
vc_paste() { printf "%s" "System clipboard not supported" >&2; exit 1; }

if [ -n "WAYLAND_DISPLAY" ] && exists wl-copy; then
    vc_copy() { exec 2>/dev/null; wl-copy; }
    vc_paste() { wl-paste; }
elif [ -n "$DISPLAY" ] && exists xsel; then
    vc_copy() { xsel -bi; }
    vc_paste() { xsel -bo; }
elif [ -n "$DISPLAY" ] && exists xclip; then
    vc_copy() { xclip -selection clipboard -i >/dev/null 2>&1; }
    vc_paste() { xclip -selection clipboard -o; }
elif exists pbcopy; then
    vc_copy() { pbcopy; }
    vc_paste() { pbpaste; }
elif [ -c /dev/clipboard ]; then
    vc_copy() { cat >/dev/clipboard; }
    vc_paste() { cat /dev/clipboard; }
elif grep -iq microsoft /proc/version 2>/dev/null && exists clip.exe; then
    vc_copy() { clip.exe; }
    vc_paste() { powershell.exe -c Get-Clipboard | sed "s/$(printf \\r)\$//"; }
elif [ "$1" = --usable ]; then
    exit 1
fi

case "$1" in
    --usable) exit 0;;
    --copy) vc_copy;;
    --paste) vc_paste;;
    *) printf "%s" "`basename $0` [--usable|--copy|--paste]" >&2; exit 1;;
esac

