Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/visual-studio"

  config.vm.network "forwarded_port", guest: 8079, host: 8080
  config.vm.network "forwarded_port", guest: 24, host: 2223
  config.vm.network "forwarded_port", guest: 3389, host: 3389

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 6144
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "provision.ps1"
end
