#!/usr/bin/env sh
#postgresql - install and configure postgresql
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }
dbdo() { [ "`uname -s`" = Darwin ] || set -- sudo -u postgres "$@"; "$@"; }
dbsql() { dbdo psql -d postgres -tAc "$@"; }

if exists pacman; then sudo pacman --needed --noconfirm -qS postgresql; fi
if exists brew; then brew install postgresql; fi

case "`uname -s`" in
Linux)
    PGROOT="${PGROOT:-/srv/postgresql}"
    sudo mkdir -p /etc/systemd/system/postgresql.service.d
    printf "[Service]\nEnvironment=PGROOT=%s\n" "$PGROOT" \
        | sudo tee /etc/systemd/system/postgresql.service.d/pgroot.conf \
        >/dev/null
    sudo mkdir -p "$PGROOT"
    sudo chown -R postgres "$PGROOT"
    ;;
Darwin)
    PGROOT="${PGROOT:-$HOME/Library/Local/srv/postgresql}"
    <postgresql/postgresql.plist \
        sed "s/\\\$PGROOT/$(echo "$PGROOT" | sed 's:[/&]:\\&:g')/" \
        > "$HOME/Library/LaunchAgents/local.postgresql.plist"
    mkdir -p "$PGROOT"
esac

if ! sudo test -f "$PGROOT/data/PG_VERSION"; then
    dbdo initdb --locale=en_US.UTF-8 -E UTF8 -D "$PGROOT/data"
fi

if exists systemctl; then sudo systemctl enable --now postgresql; fi
if exists launchctl; then
    launchctl unload "$HOME/Library/LaunchAgents/local.postgresql.plist"
    launchctl bootstrap "gui/$(id -u)" \
        "$HOME/Library/LaunchAgents/local.postgresql.plist" || true
    launchctl enable "gui/$(id -u)/local.postgresql"
    launchctl kickstart "gui/$(id -u)/local.postgresql"
    sleep 3
fi

if [ "0$(dbsql "select 1 from pg_roles where rolname='$DBUSER'")" -ne 1 ]; then
    dbsql "create role $DBUSER with login superuser createdb"
fi
dbsql "alter role $DBUSER with password '$DBPASS'"
