#!/usr/bin/env sh
#wallpaper - change wallpaper
#1: path

case "$OS" in
Darwin)
    sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db \
        "update data set value = '$1'"
    osascript -e "$(printf '%s "%s"' \
        'tell application "Finder" to set desktop picture to POSIX file' \
        "$(realpath "$1")")"
    killall Dock
    ;;
Linux)
    if [ "$XDG_SESSION_DESKTOP" = gnome ] \
            || [ "$XDG_SESSION_DESKTOP" = gnome-xorg ]; then
        gsettings set org.gnome.desktop.background picture-uri \
            "file://$(realpath "$1")"
        gsettings set org.gnome.desktop.background picture-options zoom
    elif grep -iq microsoft /proc/version 2>/dev/null; then
        set -- "$1" "$(cmd.exe /c 'echo %USERPROFILE%')/$(basename "$1")"
        set -- "$1" "$(echo "$2" | sed 's/\r//')"
        cp "$1" "$(wslpath -u "$2")"
        reg.exe add "HKCU\Control Panel\Desktop" /f /v Wallpaper /d "$2"
        rundll32.exe user32.dll, UpdatePerUserSystemParameters
    fi
    ;;
*) printf "Not supported\n" ;;
esac
