#!/usr/bin/env sh
#webserver - install webserver software
set -eu

echo() { printf "%s" "$*"; }

lineinfile() { #1: path, 2: regexp, 3: line
    [ $# -eq 2 ] && set -- "$1" "^$2\$" "${3:-$2}" || true
    if grep -qF "^$3$" "$1" 2>/dev/null; then
        return
    elif grep -q "$2" "$1" 2>/dev/null; then
        set -- "$1" "$2" "$3" "$(mktemp)"
        sed "s/.*$(echo "$2"|sed 's_/_\\/_').*/$(echo "$3"|sed 's_/_\\/_')/" \
            <"$1" >"$4"
        sudo mv "$4" "$1"
    else
        sudo sh -c 'echo "$3" >>"$1"' - "$@"
    fi
}

echo "$HOSTNAME" | grep -qF . || { echo "HOSTNAME must be a FQDN"; exit 1; }

case "$HTTPD" in
apache)
    sudo mkdir -p "/etc/httpd/conf/vhosts"
    sudo mkdir -p "/var/log/httpd"
    sudo chown -R http:http "/var/log/httpd"
    lineinfile /etc/httpd/conf/httpd.conf "Include conf/ports.conf"
    lineinfile /etc/httpd/conf/httpd.conf "^ServerName" "ServerName $HOSTNAME"
    sudo systemctl restart httpd
    ;;
nginx)
    sudo pacman -qS --needed --noconfirm nginx certbot-nginx
    sudo mkdir -p "/etc/nginx/sites-enabled"
    sudo mkdir -p "/etc/nginx/sites-available"
    sudo cp webserver/nginx.conf /etc/nginx/nginx.conf
    sudo systemctl enable nginx
    sudo systemctl reload nginx || sudo systemctl restart nginx || true
    ;;
esac


