#!/usr/bin/env sh
#user - create my account

exists() { command -v "$1" >/dev/null 2>&1; }
[ $(id -u) = 0 ] && ! exists sudo && sudo() { "$@"; }

if exists pacman; then
    pacman-key --init
    pacman-key --populate archlinux$([ "$(uname -m)" = aarch64 ] && echo arm)
fi

#Install zsh
exists pacman && sudo pacman -q --noconfirm -S --needed zsh
exists apk && sudo apk -q add zsh

#Create user
if ! id -u mil >/dev/null 2>&1; then
    PASS="$(</dev/urandom tr -cd "A-Za-z0-9" | head -c 32)"
    exists useradd && useradd -s "$(command -v zsh)" -G wheel -m mil
    exists adduser && adduser -s "$(command -v zsh)" -G wheel -D mil
    printf "%s\n%s\n" "$PASS" "$PASS" | sudo passwd mil >/dev/null 2>&1
fi

#Copy ssh public key
mkdir -p ~mil/.ssh
cp user/authorized_keys ~mil/.ssh/authorized_keys
chown -R mil ~mil/.ssh
chmod -R og-rwxs ~mil/.ssh

