#!/usr/bin/env sh
#elm - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists elm; then
    curl -Lo "$XDG_CACHE_HOME/elm.gz" "$(\
        curl -s "$(printf '%s%s' "https://api.github.com/repos/" \
                "elm/compiler/releases/latest")" \
            | sed -n '/browser_download_url/s/.*: "\(.*\)"/\1/p' \
            | grep -F "binary-for-$(\
                uname -s|sed 's/Linux/linux/;s/Darwin/mac/')")"
    gzip -cd $XDG_CACHE_HOME/elm.gz >"$XDG_BIN_HOME/elm"
    chmod +x "$XDG_BIN_HOME/elm"
fi

elm "$@"

