#!/usr/bin/env sh
#mpv - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists mpv; then
    if [ "$(uname -s)" = Darwin ]; then brew cask install mpv; fi
    if exists pacman; then sudo pacman --noconfirm --needed -qS mpv; fi
fi

mpv "$@"

