#!/usr/bin/env sh
#pacaur - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists pacaur; then
    workingdir="$(mktemp -d)"
    cd "$workingdir"
    pacman -q -S --noconfirm --needed --asdeps \
            meson gmock gtest expac jq git \
        && git clone "https://aur.archlinux.org/auracle-git.git"\
        && (cd auracle-git && makepkg -i) \
        && git clone "https://aur.archlinux.org/pacaur.git" \
        && (cd pacaur && makepkg -i)
    cd
    rm -rf "$workingdir"
fi

pacaur "$@"

