#!/usr/bin/env sh
#pip - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists pip; then
    curl https://bootstrap.pypa.io/get-pip.py | python - --user
fi

pip "$@"

