#!/usr/bin/env sh
#pip3 - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists pip3; then
    if exists pacman; then sudo pacman --needed --noconfirm -qS python;
    elif exists brew; then brew install python;
    elif exists apk; then sudo apk add -q python3;
    elif exists apt-get; then sudo apt-get install -qy python3-pip;
    else curl https://bootstrap.pypa.io/get-pip.py | python3 - --user; fi
fi

pip3 "$@"
