#!/usr/bin/env sh
#youtube-dl - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists youtube-dl; then
    if exists pacman; then sudo pacman --needed --noconfirm -qS youtube-dl;
    elif exists brew; then brew install youtube-dl;
    elif exists apk; then sudo apk add -q youtube-dl; fi
fi

youtube-dl "$@"

