#!/usr/bin/env sh
#mvln - Moves a file and creates a symbolic link in the old location
set -eu

[ "$#" -eq 2 ] || { echo "Usage: `basename "$0"` FILE NEWLOCATION"; exit 1; }

if [ -d "$2" ]; then
    mv "$1" "$2"
    ln "$(readlink -f "$2")/$(basename "$1")" "$1"
elif [ -f "$2" ]; then
    echo "Error: $2 exists" >&2
    exit 1
else
    mv "$1" "$(readlink -f "$2")"
    ln "$(readlink -f "$2")" "$1"
fi
