#!/usr/bin/env sh
#yt_cache - cache YouTube videos
set -eu

trackname() { #1:ytdl_id
    set -- "$1" "$YOUTUBE_CACHE_HOME/store/$1.info.json"
    set -- "$1" "$2" "$(<"$2" jq -r '(.artist + " - " + .track)')"
    [ "$3" != " - " ] \
        || set -- "$1" "$2" "$(<"$2" jq -r '.title' | yt_title_clean)"
    echo "$(echo "$3" | sed s_/_-_g)"
}

yt_cache_organise() {
    mkdir -p "$YOUTUBE_CACHE_HOME/named"
    cd "$YOUTUBE_CACHE_HOME/store"
    for file in *.mp4 *.mkv *.webm; do
        ln "$file" \
            "$YOUTUBE_CACHE_HOME/named/$(trackname "${file%.*}").${file##*.}" \
                || true
    done
}

yt_cache_dl() {
    mkdir -p "$YOUTUBE_CACHE_HOME/store"
    cd "$YOUTUBE_CACHE_HOME/store"
    youtube-dl \
        --download-archive "$YOUTUBE_CACHE_HOME/state" \
        --write-info-json \
        --write-description \
        --write-thumbnail \
        -o '%(extractor)s %(id)s.%(ext)s' "$@"
}

YOUTUBE_CACHE_HOME="${YOUTUBE_CACHE_HOME:-$XDG_DATA_HOME/yt_cache}"
yt_cache_"$@"
