#!/usr/bin/env sh
#ssl - set up certificate for site
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if exists apt-get; then
    sudo apt-get install software-properties-common
    sudo add-apt-repository universe
    sudo apt-get update
    sudo apt-get install -yq certbot python3-certbot-nginx
elif exists pacman; then
    sudo pacman -qS --needed --noconfirm certbot-nginx
fi
echo "$SITENAME" | grep -qF . || { echo "SITENAME must be a FQDN"; exit 1; }
if sudo test ! -d "/etc/letsencrypt/live/$SITENAME"; then
    sudo certbot certonly -n --nginx --agree-tos --no-eff-email \
        -m "root@$SITENAME" -d "$SITENAME" --cert-name "$SITENAME"
fi
sudo certbot install -n --nginx --reinstall \
    -d "$SITENAME" --cert-name "$SITENAME" 

sudo systemctl reload nginx
